-- Table: users
DROP TABLE IF EXISTS users_backup;
CREATE TABLE users_backup AS SELECT * FROM users;

-- Table: waitlist_responses
DROP TABLE IF EXISTS waitlist_responses_backup;
CREATE TABLE waitlist_responses_backup AS SELECT * FROM waitlist_responses;

-- Data for table: waitlist_responses
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (1, 'Test User Complete', 'test2@example.com', 'Engineer', '25-35', '5_times_daily', 'basic', 'sometimes', 'very_important', 'understanding_arabic', 'translation_apps', 'basic_knowledge', 'very_meaningful', '["live_translation","pronunciation_guidance"]', 'very_likely', 'This sounds amazing!', 'yes_happy_to_help', 'yes_interested', NULL, '2025-07-13T16:18:36.303Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (2, 'Farhad Malik', 'farhad@the-maliks.com', 'CEO', '36-45', '3_4_times_daily', 'basic', 'sometimes', 'very_important', 'lack_resources', 'books_resources', 'some_experience', 'helpful_addition', '["live_translation","pronunciation_guidance","qibla_indicator"]', 'very_likely', 'Test', 'maybe_timing_dependent', 'yes_interested', '', '2025-07-13T16:22:45.812Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (3, 'Ibrahim Malik', 'ibrahim.malik.1492@gmail.com', 'CEO', '36-45', '3_4_times_daily', 'basic', 'often', 'very_important', 'finding_time', 'books_resources', 'some_experience', 'very_meaningful', '["qibla_indicator","pronunciation_guidance","live_translation"]', 'very_likely', 'Test', 'yes_happy_to_help', 'yes_interested', '', '2025-07-13T16:24:07.871Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (4, 'Omar Shahid', 'omarshahid99@gmail.com', 'Founder ', '26-35', '5_times_daily', 'basic', 'often', 'very_important', 'finding_time', 'translation_apps', 'heard_about_it', 'helpful_addition', '["tajweed_correction","history_visualization","live_translation"]', 'moderately_likely', '', 'maybe_timing_dependent', 'yes_interested', '', '2025-07-13T16:57:04.720Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (5, 'Farhad Malik', 'farhad@propertychameleon.co.uk', 'CEO', '46-55', '5_times_daily', 'basic', 'sometimes', 'very_important', 'finding_time', 'study_before_after', 'some_experience', 'helpful_addition', '["live_translation","tajweed_correction","history_visualization"]', 'very_likely', 'Test', 'yes_happy_to_help', 'yes_interested', '', '2025-07-13T17:33:31.263Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (6, 'Farhad Malik', 'farhad@propertychameleon.co.uk', 'CEO', '46-55', 'weekly', 'good', 'sometimes', 'moderately_important', 'finding_time', 'books_resources', 'some_experience', 'very_meaningful', '["live_translation","qibla_indicator","history_visualization"]', 'extremely_likely', 'test', 'yes_happy_to_help', 'yes_interested', '', '2025-07-13T17:36:32.306Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (7, 'Test User', 'test@example.com', NULL, '25-34', '5-times', 'none', 'hard', 'important', 'focus', 'books', 'none', 'very-interested', '["translation"]', NULL, NULL, 'yes', 'yes', NULL, '2025-07-15T07:59:01.711Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (8, 'Farhad Malik', 'farhad@the-maliks.com', 'CEO', '36-45', '1_2_times_daily', 'good', 'often', 'moderately_important', 'lack_resources', 'memorized_translations', 'some_experience', 'very_meaningful', '["pronunciation_guidance","qibla_indicator","prayer_times"]', 'very_likely', 'Test', 'maybe_timing_dependent', 'maybe_later', '', '2025-07-15T08:01:40.340Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (9, 'Farhad Malik', 'farhad@the-maliks.com', 'CEO', '26-35', '3_4_times_daily', 'good', 'often', 'moderately_important', 'lack_resources', 'memorized_translations', 'some_experience', 'very_meaningful', '["qibla_indicator","prayer_times","hadith_overlay"]', 'very_likely', 'Test', 'maybe_timing_dependent', 'maybe_later', '', '2025-07-15T08:13:24.788Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (10, 'Farhad Malik', 'farhad@the-maliks.com', 'CEO', '36-45', '3_4_times_daily', 'good', 'often', 'moderately_important', 'lack_resources', 'books_resources', 'basic_knowledge', 'very_meaningful', '["prayer_times","hadith_overlay","tajweed_correction"]', 'moderately_likely', 'Curtious', 'maybe_timing_dependent', 'maybe_later', '', '2025-07-15T08:31:17.635Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (11, 'Farhad Malik', 'farhad@the-maliks.com', 'CEO', '26-35', '1_2_times_daily', 'basic', 'often', 'moderately_important', 'lack_resources', 'books_resources', 'some_experience', 'very_meaningful', '["qibla_indicator","prayer_times","hadith_overlay"]', 'very_likely', 'Test', 'maybe_timing_dependent', 'maybe_later', '', '2025-07-15T09:47:44.197Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (12, 'Test User', 'test@example.com', NULL, '25-34', '5-times', 'none', 'hard', 'important', 'focus', 'books', 'none', 'very-interested', '["translation"]', NULL, NULL, 'yes', 'yes', NULL, '2025-07-15T16:11:14.818Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (13, 'Micheal Oguntayo', 'oguntayomicheal1@gmail.com', 'Student', '56-65', 'rarely', 'very_limited', 'never', 'not_important', 'staying_consistent', 'other_method', 'completely_new', 'unsure', '["history_visualization"]', 'slightly_likely', '', 'maybe_timing_dependent', 'no_thank_you', '', '2025-07-16T09:05:42.359Z');
INSERT INTO waitlist_responses_backup (id, full_name, email, role, age, prayer_frequency, arabic_understanding, understanding_difficulty, importance, learning_struggle, current_approach, ar_experience, ar_interest, features, likelihood, additional_feedback, interview_willingness, investor_presentation, additional_comments, created_at) VALUES (14, 'Test Ibrahim Malik', 'test.ibrahim@example.com', 'Muslim', '25-34', '5_times_daily', 'basic', 'sometimes', 'important', 'finding_time', 'apps', 'none', 'very_meaningful', '["live_translation"]', 'likely', 'Test submission', 'yes', 'yes', 'Testing new submissions', '2025-07-16T16:25:49.027Z');

